"""Add device_id to WorkOrder

Revision ID: 6f907ff1cd06
Revises: 3a936de1c0b9
Create Date: 2025-06-17 16:19:55.314724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f907ff1cd06'
down_revision: Union[str, None] = '3a936de1c0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('device_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'work_orders', 'devices', ['device_id'], ['device_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_column('work_orders', 'device_id')
    # ### end Alembic commands ###
