"""initial_migration

Revision ID: da801855bdf6
Revises: 
Create Date: 2025-06-13 13:52:51.564647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da801855bdf6'

down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('anomaly_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('anomaly_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notification_templates',
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('template_key', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('EMAIL', 'SMS', 'PUSH', 'IN_APP', name='notificationtype'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('template_key')
    )
    op.create_table('ocr_techniques',
    sa.Column('ocr_id', sa.BigInteger(), nullable=False),
    sa.Column('technique_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ocr_id'),
    sa.UniqueConstraint('technique_name')
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('subcontractor_companies',
    sa.Column('subcontractor_id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('subcontractor_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.String(length=75), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('profile_image', sa.String(length=256), nullable=True),
    sa.Column('preferred_lang', sa.String(length=10), nullable=True),
    sa.Column('timezone_id', sa.String(length=75), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', 'DEACTIVATED', name='userstatus'), nullable=True),
    sa.Column('external_id', sa.String(length=75), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('activation_key', sa.String(length=20), nullable=True),
    sa.Column('reset_key', sa.String(length=20), nullable=True),
    sa.Column('login_ip', sa.String(length=75), nullable=True),
    sa.Column('last_login_ip', sa.String(length=75), nullable=True),
    sa.Column('login_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reset_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('auth_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_auth_tokens_id'), 'auth_tokens', ['id'], unique=False)
    op.create_table('picture_quality_metrics',
    sa.Column('metric_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('total_uploaded', sa.Integer(), nullable=True),
    sa.Column('total_ok', sa.Integer(), nullable=True),
    sa.Column('total_not_ok', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('support_tickets',
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('system_feedback',
    sa.Column('feedback_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('user_activity_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_auth_metadata',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('external_user_id', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_auth_providers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=150), nullable=False),
    sa.Column('provider_username', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification_preferences',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_notifications',
    sa.Column('notification_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notification_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.template_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_status_audit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('changed_by', sa.String(length=50), nullable=False),
    sa.Column('old_status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', 'DEACTIVATED', name='userstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', 'DEACTIVATED', name='userstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_centres',
    sa.Column('work_centre_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('work_centre_id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('devices',
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'UNREGISTERED', 'IN_SERVICE', 'OUT_OF_SERVICE', name='devicestatus'), nullable=True),
    sa.Column('last_communication', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('work_center_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centres.work_centre_id'], ),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('feedback_attachments',
    sa.Column('attachment_id', sa.BigInteger(), nullable=False),
    sa.Column('feedback_id', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['system_feedback.feedback_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('notification_history',
    sa.Column('history_id', sa.BigInteger(), nullable=False),
    sa.Column('notification_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('delivery_timestamp', sa.DateTime(), nullable=True),
    sa.Column('delivery_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['user_notifications.notification_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('ticket_attachments',
    sa.Column('attachment_id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.ticket_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('ticket_messages',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('work_centre_subcontractors',
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('work_centre_id', sa.BigInteger(), nullable=True),
    sa.Column('subcontractor_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_by', sa.BigInteger(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractor_companies.subcontractor_id'], ),
    sa.ForeignKeyConstraint(['work_centre_id'], ['work_centres.work_centre_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('work_orders',
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('wo_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_order_type', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'REJECTED', name='workorderstatus'), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('work_centre_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['work_centre_id'], ['work_centres.work_centre_id'], ),
    sa.PrimaryKeyConstraint('work_order_id'),
    sa.UniqueConstraint('wo_number')
    )
    op.create_table('device_artifacts',
    sa.Column('artifact_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.Enum('PURCHASED', 'LEASED', 'OWNED', name='devicesourcetype'), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('source_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_destination', sa.Enum('REGIONAL_PLANET', 'CENTER_PLANET', 'OTHER', name='devicesourcedestination'), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_table('device_assignments',
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.Enum('TECHNICIAN', 'SUPERVISOR', 'OTHER', name='deviceassignmentrole'), nullable=True),
    sa.Column('assigned_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_by_role', sa.Enum('TECHNICIAN', 'SUPERVISOR', 'OTHER', name='deviceassignmentrole'), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('device_health_logs',
    sa.Column('health_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=True),
    sa.Column('battery_status', sa.String(length=20), nullable=True),
    sa.Column('network_status', sa.String(length=20), nullable=True),
    sa.Column('touch_screen', sa.String(length=20), nullable=True),
    sa.Column('camera_status', sa.String(length=20), nullable=True),
    sa.Column('gps_status', sa.String(length=20), nullable=True),
    sa.Column('logged_by', sa.BigInteger(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('health_id')
    )
    op.create_table('device_status_audit',
    sa.Column('audit_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=True),
    sa.Column('status_before', sa.String(length=50), nullable=True),
    sa.Column('status_after', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('picture_metadata',
    sa.Column('picture_id', sa.BigInteger(), nullable=False),
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('request_type', sa.Enum('NEW_CONNECTION', 'SUBSCRIPTION', 'COMPLAINT', 'TERMINATION', 'OTHER', name='requesttype'), nullable=False),
    sa.Column('meter_number', sa.String(length=100), nullable=True),
    sa.Column('supply_point_number', sa.String(length=100), nullable=True),
    sa.Column('cycle', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('picture_id')
    )
    op.create_table('work_order_acknowledgments',
    sa.Column('ack_id', sa.BigInteger(), nullable=False),
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_signature', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('ack_id')
    )
    op.create_table('work_order_assignments',
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_by', sa.BigInteger(), nullable=False),
    sa.Column('reassigned', sa.Boolean(), nullable=True),
    sa.Column('reassignment_reason', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('work_order_attachments',
    sa.Column('attachment_id', sa.BigInteger(), nullable=False),
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('work_order_data_capture',
    sa.Column('capture_id', sa.BigInteger(), nullable=False),
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('request_type', sa.Enum('NEW_CONNECTION', 'SUBSCRIPTION', 'COMPLAINT', 'TERMINATION', 'OTHER', name='requesttype'), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('offline_captured', sa.Boolean(), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('capture_id')
    )
    op.create_table('work_order_execution',
    sa.Column('execution_id', sa.BigInteger(), nullable=False),
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('gps_lat', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('gps_long', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('parts_used', sa.Text(), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_table('work_order_feedback',
    sa.Column('feedback_id', sa.BigInteger(), nullable=False),
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('feedback_by', sa.BigInteger(), nullable=True),
    sa.Column('feedback_type', sa.String(length=20), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('feedback_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('work_order_notes',
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('note_type', sa.String(length=20), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_table('work_order_status_logs',
    sa.Column('status_log_id', sa.BigInteger(), nullable=False),
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('status_log_id')
    )
    op.create_table('data_capture_validation_logs',
    sa.Column('validation_id', sa.BigInteger(), nullable=False),
    sa.Column('capture_id', sa.BigInteger(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['work_order_data_capture.capture_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('validation_id')
    )
    op.create_table('offline_capture_queue',
    sa.Column('queue_id', sa.BigInteger(), nullable=False),
    sa.Column('capture_id', sa.BigInteger(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['work_order_data_capture.capture_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_table('picture_annotation',
    sa.Column('annotation_id', sa.BigInteger(), nullable=False),
    sa.Column('picture_id', sa.BigInteger(), nullable=True),
    sa.Column('annotated_by', sa.BigInteger(), nullable=True),
    sa.Column('ocr_id', sa.BigInteger(), nullable=True),
    sa.Column('annotation_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['annotated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ocr_id'], ['ocr_techniques.ocr_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['picture_id'], ['picture_metadata.picture_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('annotation_id')
    )
    op.create_table('picture_download_log',
    sa.Column('download_id', sa.BigInteger(), nullable=False),
    sa.Column('picture_id', sa.BigInteger(), nullable=True),
    sa.Column('downloaded_by', sa.BigInteger(), nullable=True),
    sa.Column('is_batch', sa.Boolean(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['downloaded_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['picture_id'], ['picture_metadata.picture_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('download_id')
    )
    op.create_table('picture_qualification',
    sa.Column('qualification_id', sa.BigInteger(), nullable=False),
    sa.Column('picture_id', sa.BigInteger(), nullable=True),
    sa.Column('qualified_by', sa.BigInteger(), nullable=True),
    sa.Column('qualification_status', sa.String(length=10), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('qualified_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['picture_id'], ['picture_metadata.picture_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qualified_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('qualification_id')
    )
    op.create_table('work_order_execution_anomalies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('execution_id', sa.BigInteger(), nullable=True),
    sa.Column('anomaly_id', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.anomaly_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['execution_id'], ['work_order_execution.execution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_order_execution_anomalies')
    op.drop_table('picture_qualification')
    op.drop_table('picture_download_log')
    op.drop_table('picture_annotation')
    op.drop_table('offline_capture_queue')
    op.drop_table('data_capture_validation_logs')
    op.drop_table('work_order_status_logs')
    op.drop_table('work_order_notes')
    op.drop_table('work_order_feedback')
    op.drop_table('work_order_execution')
    op.drop_table('work_order_data_capture')
    op.drop_table('work_order_attachments')
    op.drop_table('work_order_assignments')
    op.drop_table('work_order_acknowledgments')
    op.drop_table('picture_metadata')
    op.drop_table('device_status_audit')
    op.drop_table('device_health_logs')
    op.drop_table('device_assignments')
    op.drop_table('device_artifacts')
    op.drop_table('work_orders')
    op.drop_table('work_centre_subcontractors')
    op.drop_table('ticket_messages')
    op.drop_table('ticket_attachments')
    op.drop_table('notification_history')
    op.drop_table('feedback_attachments')
    op.drop_table('devices')
    op.drop_table('work_centres')
    op.drop_table('user_status_audit')
    op.drop_table('user_roles')
    op.drop_table('user_notifications')
    op.drop_table('user_notification_preferences')
    op.drop_table('user_auth_providers')
    op.drop_table('user_auth_metadata')
    op.drop_table('user_activity_logs')
    op.drop_table('system_feedback')
    op.drop_table('support_tickets')
    op.drop_table('role_permissions')
    op.drop_table('picture_quality_metrics')
    op.drop_index(op.f('ix_auth_tokens_id'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_table('users')
    op.drop_table('subcontractor_companies')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('ocr_techniques')
    op.drop_table('notification_templates')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
